// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.11
// source: protocol/model.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NullMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NullMessage) Reset() {
	*x = NullMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullMessage) ProtoMessage() {}

func (x *NullMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullMessage.ProtoReflect.Descriptor instead.
func (*NullMessage) Descriptor() ([]byte, []int) {
	return file_protocol_model_proto_rawDescGZIP(), []int{0}
}

type AccessRecordsToInfluxDB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName  string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Domain    string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Ip        string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	ProxyType string `protobuf:"bytes,4,opt,name=proxy_type,json=proxyType,proto3" json:"proxy_type,omitempty"`
}

func (x *AccessRecordsToInfluxDB) Reset() {
	*x = AccessRecordsToInfluxDB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessRecordsToInfluxDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRecordsToInfluxDB) ProtoMessage() {}

func (x *AccessRecordsToInfluxDB) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRecordsToInfluxDB.ProtoReflect.Descriptor instead.
func (*AccessRecordsToInfluxDB) Descriptor() ([]byte, []int) {
	return file_protocol_model_proto_rawDescGZIP(), []int{1}
}

func (x *AccessRecordsToInfluxDB) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AccessRecordsToInfluxDB) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AccessRecordsToInfluxDB) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AccessRecordsToInfluxDB) GetProxyType() string {
	if x != nil {
		return x.ProxyType
	}
	return ""
}

type AuthEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are assignable to Data:
	//
	//	*AuthEvent_AuthInfo
	//	*AuthEvent_Ipv6AuthInfo
	//	*AuthEvent_Ipv6AuthInfoList
	//	*AuthEvent_DisconnectInfo
	//	*AuthEvent_ShadowSocksData
	Data isAuthEvent_Data `protobuf_oneof:"data"`
}

func (x *AuthEvent) Reset() {
	*x = AuthEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthEvent) ProtoMessage() {}

func (x *AuthEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthEvent.ProtoReflect.Descriptor instead.
func (*AuthEvent) Descriptor() ([]byte, []int) {
	return file_protocol_model_proto_rawDescGZIP(), []int{2}
}

func (x *AuthEvent) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (m *AuthEvent) GetData() isAuthEvent_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *AuthEvent) GetAuthInfo() *AuthInfo {
	if x, ok := x.GetData().(*AuthEvent_AuthInfo); ok {
		return x.AuthInfo
	}
	return nil
}

func (x *AuthEvent) GetIpv6AuthInfo() *Ipv6AuthInfo {
	if x, ok := x.GetData().(*AuthEvent_Ipv6AuthInfo); ok {
		return x.Ipv6AuthInfo
	}
	return nil
}

func (x *AuthEvent) GetIpv6AuthInfoList() *Ipv6AuthInfoList {
	if x, ok := x.GetData().(*AuthEvent_Ipv6AuthInfoList); ok {
		return x.Ipv6AuthInfoList
	}
	return nil
}

func (x *AuthEvent) GetDisconnectInfo() *DisconnectInfo {
	if x, ok := x.GetData().(*AuthEvent_DisconnectInfo); ok {
		return x.DisconnectInfo
	}
	return nil
}

func (x *AuthEvent) GetShadowSocksData() *ShadowSocksData {
	if x, ok := x.GetData().(*AuthEvent_ShadowSocksData); ok {
		return x.ShadowSocksData
	}
	return nil
}

type isAuthEvent_Data interface {
	isAuthEvent_Data()
}

type AuthEvent_AuthInfo struct {
	AuthInfo *AuthInfo `protobuf:"bytes,2,opt,name=auth_info,json=authInfo,proto3,oneof"`
}

type AuthEvent_Ipv6AuthInfo struct {
	Ipv6AuthInfo *Ipv6AuthInfo `protobuf:"bytes,3,opt,name=ipv6_auth_info,json=ipv6AuthInfo,proto3,oneof"`
}

type AuthEvent_Ipv6AuthInfoList struct {
	Ipv6AuthInfoList *Ipv6AuthInfoList `protobuf:"bytes,4,opt,name=ipv6_auth_info_list,json=ipv6AuthInfoList,proto3,oneof"`
}

type AuthEvent_DisconnectInfo struct {
	DisconnectInfo *DisconnectInfo `protobuf:"bytes,5,opt,name=disconnect_info,json=disconnectInfo,proto3,oneof"`
}

type AuthEvent_ShadowSocksData struct {
	ShadowSocksData *ShadowSocksData `protobuf:"bytes,6,opt,name=shadow_socks_data,json=shadowSocksData,proto3,oneof"`
}

func (*AuthEvent_AuthInfo) isAuthEvent_Data() {}

func (*AuthEvent_Ipv6AuthInfo) isAuthEvent_Data() {}

func (*AuthEvent_Ipv6AuthInfoList) isAuthEvent_Data() {}

func (*AuthEvent_DisconnectInfo) isAuthEvent_Data() {}

func (*AuthEvent_ShadowSocksData) isAuthEvent_Data() {}

type AuthInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username      string                  `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`                                //账号
	Password      string                  `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                                //密码
	ProxyUsername string                  `protobuf:"bytes,3,opt,name=proxy_username,json=proxyUsername,proto3" json:"proxy_username,omitempty"` //代理账号
	ProxyPassword string                  `protobuf:"bytes,4,opt,name=proxy_password,json=proxyPassword,proto3" json:"proxy_password,omitempty"` //代理密码
	S5Addr        string                  `protobuf:"bytes,5,opt,name=s5_addr,json=s5Addr,proto3" json:"s5_addr,omitempty"`                      //s5代理地址 ip:端口
	HttpAddr      string                  `protobuf:"bytes,6,opt,name=http_addr,json=httpAddr,proto3" json:"http_addr,omitempty"`                //http代理  ip:端口
	UpdateUnix    int64                   `protobuf:"varint,7,opt,name=update_unix,json=updateUnix,proto3" json:"update_unix,omitempty"`
	Ips           map[string]*NullMessage `protobuf:"bytes,8,rep,name=ips,proto3" json:"ips,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //ip数组
}

func (x *AuthInfo) Reset() {
	*x = AuthInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthInfo) ProtoMessage() {}

func (x *AuthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthInfo.ProtoReflect.Descriptor instead.
func (*AuthInfo) Descriptor() ([]byte, []int) {
	return file_protocol_model_proto_rawDescGZIP(), []int{3}
}

func (x *AuthInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthInfo) GetProxyUsername() string {
	if x != nil {
		return x.ProxyUsername
	}
	return ""
}

func (x *AuthInfo) GetProxyPassword() string {
	if x != nil {
		return x.ProxyPassword
	}
	return ""
}

func (x *AuthInfo) GetS5Addr() string {
	if x != nil {
		return x.S5Addr
	}
	return ""
}

func (x *AuthInfo) GetHttpAddr() string {
	if x != nil {
		return x.HttpAddr
	}
	return ""
}

func (x *AuthInfo) GetUpdateUnix() int64 {
	if x != nil {
		return x.UpdateUnix
	}
	return 0
}

func (x *AuthInfo) GetIps() map[string]*NullMessage {
	if x != nil {
		return x.Ips
	}
	return nil
}

type Ipv6AuthInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` //账号
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` //密码
	Ip       string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`             //ip
	Banned   bool   `protobuf:"varint,4,opt,name=banned,proto3" json:"banned,omitempty"`    // 是否被封禁
}

func (x *Ipv6AuthInfo) Reset() {
	*x = Ipv6AuthInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ipv6AuthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ipv6AuthInfo) ProtoMessage() {}

func (x *Ipv6AuthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ipv6AuthInfo.ProtoReflect.Descriptor instead.
func (*Ipv6AuthInfo) Descriptor() ([]byte, []int) {
	return file_protocol_model_proto_rawDescGZIP(), []int{4}
}

func (x *Ipv6AuthInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Ipv6AuthInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Ipv6AuthInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Ipv6AuthInfo) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

type Ipv6AuthInfoList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ipv6AuthInfoList []*Ipv6AuthInfo `protobuf:"bytes,1,rep,name=ipv6_auth_info_list,json=ipv6AuthInfoList,proto3" json:"ipv6_auth_info_list,omitempty"`
}

func (x *Ipv6AuthInfoList) Reset() {
	*x = Ipv6AuthInfoList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ipv6AuthInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ipv6AuthInfoList) ProtoMessage() {}

func (x *Ipv6AuthInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ipv6AuthInfoList.ProtoReflect.Descriptor instead.
func (*Ipv6AuthInfoList) Descriptor() ([]byte, []int) {
	return file_protocol_model_proto_rawDescGZIP(), []int{5}
}

func (x *Ipv6AuthInfoList) GetIpv6AuthInfoList() []*Ipv6AuthInfo {
	if x != nil {
		return x.Ipv6AuthInfoList
	}
	return nil
}

type DisconnectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` //账号
	Ips      []string `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
}

func (x *DisconnectInfo) Reset() {
	*x = DisconnectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_model_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisconnectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectInfo) ProtoMessage() {}

func (x *DisconnectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_model_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectInfo.ProtoReflect.Descriptor instead.
func (*DisconnectInfo) Descriptor() ([]byte, []int) {
	return file_protocol_model_proto_rawDescGZIP(), []int{6}
}

func (x *DisconnectInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DisconnectInfo) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type ShadowSocksData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip       string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ShadowSocksData) Reset() {
	*x = ShadowSocksData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_model_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShadowSocksData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShadowSocksData) ProtoMessage() {}

func (x *ShadowSocksData) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_model_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShadowSocksData.ProtoReflect.Descriptor instead.
func (*ShadowSocksData) Descriptor() ([]byte, []int) {
	return file_protocol_model_proto_rawDescGZIP(), []int{7}
}

func (x *ShadowSocksData) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ShadowSocksData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type BlackListAccessLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site        string `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`                                   // 网址
	AccountType int32  `protobuf:"varint,2,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"` // 账号类型 0 动态 1 静态
	Account     string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`                             //账号
	ExitIp      string `protobuf:"bytes,4,opt,name=exit_ip,json=exitIp,proto3" json:"exit_ip,omitempty"`                 // 出口ip
}

func (x *BlackListAccessLog) Reset() {
	*x = BlackListAccessLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_model_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlackListAccessLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackListAccessLog) ProtoMessage() {}

func (x *BlackListAccessLog) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_model_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackListAccessLog.ProtoReflect.Descriptor instead.
func (*BlackListAccessLog) Descriptor() ([]byte, []int) {
	return file_protocol_model_proto_rawDescGZIP(), []int{8}
}

func (x *BlackListAccessLog) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *BlackListAccessLog) GetAccountType() int32 {
	if x != nil {
		return x.AccountType
	}
	return 0
}

func (x *BlackListAccessLog) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *BlackListAccessLog) GetExitIp() string {
	if x != nil {
		return x.ExitIp
	}
	return ""
}

var File_protocol_model_proto protoreflect.FileDescriptor

var file_protocol_model_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x4e, 0x75, 0x6c, 0x6c, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x7d, 0x0a, 0x17, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x54, 0x6f, 0x49, 0x6e, 0x66, 0x6c, 0x75, 0x78, 0x44, 0x42,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x22, 0xc8, 0x02, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x35, 0x0a, 0x0e, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x49, 0x70, 0x76, 0x36, 0x41,
	0x75, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0c, 0x69, 0x70, 0x76, 0x36, 0x41,
	0x75, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x42, 0x0a, 0x13, 0x69, 0x70, 0x76, 0x36, 0x5f,
	0x61, 0x75, 0x74, 0x68, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x49, 0x70, 0x76, 0x36, 0x41, 0x75, 0x74, 0x68, 0x49,
	0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x10, 0x69, 0x70, 0x76, 0x36, 0x41,
	0x75, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0f, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3e, 0x0a, 0x11, 0x73, 0x68, 0x61, 0x64, 0x6f,
	0x77, 0x5f, 0x73, 0x6f, 0x63, 0x6b, 0x73, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x53, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x53, 0x6f, 0x63, 0x6b, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0f, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x53, 0x6f,
	0x63, 0x6b, 0x73, 0x44, 0x61, 0x74, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0xd3, 0x02, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x35, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x35, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x68,
	0x74, 0x74, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x68, 0x74, 0x74, 0x70, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x78, 0x12, 0x24, 0x0a, 0x03, 0x69, 0x70, 0x73,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x49, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x69, 0x70, 0x73, 0x1a,
	0x44, 0x0a, 0x08, 0x49, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4e,
	0x75, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x6e, 0x0a, 0x0c, 0x49, 0x70, 0x76, 0x36, 0x41, 0x75, 0x74,
	0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x62,
	0x61, 0x6e, 0x6e, 0x65, 0x64, 0x22, 0x50, 0x0a, 0x10, 0x49, 0x70, 0x76, 0x36, 0x41, 0x75, 0x74,
	0x68, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x13, 0x69, 0x70, 0x76,
	0x36, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x49, 0x70, 0x76, 0x36, 0x41, 0x75, 0x74,
	0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x10, 0x69, 0x70, 0x76, 0x36, 0x41, 0x75, 0x74, 0x68, 0x49,
	0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x0e, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x03, 0x69, 0x70, 0x73, 0x22, 0x3d, 0x0a, 0x0f, 0x53, 0x68, 0x61, 0x64, 0x6f,
	0x77, 0x53, 0x6f, 0x63, 0x6b, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x7e, 0x0a, 0x12, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x78, 0x69, 0x74, 0x49, 0x70, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_model_proto_rawDescOnce sync.Once
	file_protocol_model_proto_rawDescData = file_protocol_model_proto_rawDesc
)

func file_protocol_model_proto_rawDescGZIP() []byte {
	file_protocol_model_proto_rawDescOnce.Do(func() {
		file_protocol_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_model_proto_rawDescData)
	})
	return file_protocol_model_proto_rawDescData
}

var file_protocol_model_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protocol_model_proto_goTypes = []interface{}{
	(*NullMessage)(nil),             // 0: NullMessage
	(*AccessRecordsToInfluxDB)(nil), // 1: AccessRecordsToInfluxDB
	(*AuthEvent)(nil),               // 2: AuthEvent
	(*AuthInfo)(nil),                // 3: AuthInfo
	(*Ipv6AuthInfo)(nil),            // 4: Ipv6AuthInfo
	(*Ipv6AuthInfoList)(nil),        // 5: Ipv6AuthInfoList
	(*DisconnectInfo)(nil),          // 6: DisconnectInfo
	(*ShadowSocksData)(nil),         // 7: ShadowSocksData
	(*BlackListAccessLog)(nil),      // 8: BlackListAccessLog
	nil,                             // 9: AuthInfo.IpsEntry
}
var file_protocol_model_proto_depIdxs = []int32{
	3, // 0: AuthEvent.auth_info:type_name -> AuthInfo
	4, // 1: AuthEvent.ipv6_auth_info:type_name -> Ipv6AuthInfo
	5, // 2: AuthEvent.ipv6_auth_info_list:type_name -> Ipv6AuthInfoList
	6, // 3: AuthEvent.disconnect_info:type_name -> DisconnectInfo
	7, // 4: AuthEvent.shadow_socks_data:type_name -> ShadowSocksData
	9, // 5: AuthInfo.ips:type_name -> AuthInfo.IpsEntry
	4, // 6: Ipv6AuthInfoList.ipv6_auth_info_list:type_name -> Ipv6AuthInfo
	0, // 7: AuthInfo.IpsEntry.value:type_name -> NullMessage
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_protocol_model_proto_init() }
func file_protocol_model_proto_init() {
	if File_protocol_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessRecordsToInfluxDB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ipv6AuthInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_model_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ipv6AuthInfoList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_model_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisconnectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_model_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShadowSocksData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_model_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlackListAccessLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protocol_model_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*AuthEvent_AuthInfo)(nil),
		(*AuthEvent_Ipv6AuthInfo)(nil),
		(*AuthEvent_Ipv6AuthInfoList)(nil),
		(*AuthEvent_DisconnectInfo)(nil),
		(*AuthEvent_ShadowSocksData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_model_proto_goTypes,
		DependencyIndexes: file_protocol_model_proto_depIdxs,
		MessageInfos:      file_protocol_model_proto_msgTypes,
	}.Build()
	File_protocol_model_proto = out.File
	file_protocol_model_proto_rawDesc = nil
	file_protocol_model_proto_goTypes = nil
	file_protocol_model_proto_depIdxs = nil
}
